#!/bin/sh

sudo apt-get update
sudo apt-get install -yy \
  asciidoctor \
  zsh xz-utils liblz4-tool musl-tools \
  git \
  cmake \
  g++ \
  pkg-config \
  libssl-dev \
  curl \
  llvm \
  clang \
  libudev-dev

